spring:
  application:
    name: characohol-api
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
