spring:
  application:
    name: characohol-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # ?? update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
